<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-08T16:46:23 IST" name="Default suite" finished-at="2022-12-08T16:47:22 IST" duration-ms="58401">
    <groups>
    </groups>
    <test started-at="2022-12-08T16:46:23 IST" name="Default test" finished-at="2022-12-08T16:47:22 IST" duration-ms="58401">
      <class name="testClasses.LoginTestWithTestNG">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:testClasses.LoginTestWithTestNG@6e6f2380]" started-at="2022-12-08T16:46:23 IST" name="launchBrowser" finished-at="2022-12-08T16:46:35 IST" duration-ms="11391" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="verifyLoginpageTitle()[pri:0, instance:testClasses.LoginTestWithTestNG@6e6f2380]" started-at="2022-12-08T16:46:35 IST" name="verifyLoginpageTitle" finished-at="2022-12-08T16:46:35 IST" duration-ms="34" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginpageTitle -->
        <test-method signature="verifyWhetherLoginIsSuccessful()[pri:0, instance:testClasses.LoginTestWithTestNG@6e6f2380]" started-at="2022-12-08T16:46:35 IST" name="verifyWhetherLoginIsSuccessful" finished-at="2022-12-08T16:46:36 IST" duration-ms="1258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWhetherLoginIsSuccessful -->
        <test-method signature="verifyWhetherLogoutIsSuccessful()[pri:0, instance:testClasses.LoginTestWithTestNG@6e6f2380]" started-at="2022-12-08T16:46:36 IST" name="verifyWhetherLogoutIsSuccessful" finished-at="2022-12-08T16:47:21 IST" duration-ms="44743" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your Stores] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your Stores] but found [Your Store]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testClasses.LoginTestWithTestNG.verifyWhetherLogoutIsSuccessful(LoginTestWithTestNG.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWhetherLogoutIsSuccessful -->
        <test-method is-config="true" signature="terminateBrowser()[pri:0, instance:testClasses.LoginTestWithTestNG@6e6f2380]" started-at="2022-12-08T16:47:21 IST" name="terminateBrowser" finished-at="2022-12-08T16:47:22 IST" duration-ms="837" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
      </class> <!-- testClasses.LoginTestWithTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
